/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Flashcard {
  content_back: string;
  content_front: string;
  id: number;
  interval: number;
  next_review: string;
  [k: string]: unknown;
}
