/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Review {
  card_id: number;
  correct: boolean;
  duration_back: number;
  duration_front: number;
  id: number;
  interval: number;
  review_date: string;
  [k: string]: unknown;
}
